#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.4.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'FileNodesApi' {
    Context 'Invoke-DeviceType6GetNodeById' {
        It 'Test Invoke-DeviceType6GetNodeById' {
            #$TestResult = Invoke-DeviceType6GetNodeById -SystemUuid "TEST_VALUE" -NodeUuid "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-DeviceType6GetNodes' {
        It 'Test Invoke-DeviceType6GetNodes' {
            #$TestResult = Invoke-DeviceType6GetNodes -SystemUuid "TEST_VALUE" -Limit "TEST_VALUE" -Offset "TEST_VALUE" -Filter "TEST_VALUE" -Sort "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
