#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.3.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Average performance statistics

.PARAMETER AvgOf1day
Average of 1 day
.PARAMETER AvgOf1hour
Average of 1 hour
.PARAMETER AvgOf8hours
Average of 8 hours
.PARAMETER AvgOfLatest
Average of latest
.OUTPUTS

Statistics<PSCustomObject>
#>

function Initialize-Statistics {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Double]]
        ${AvgOf1day},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Double]]
        ${AvgOf1hour},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Double]]
        ${AvgOf8hours},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Double]]
        ${AvgOfLatest}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => Statistics' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "avgOf1day" = ${AvgOf1day}
            "avgOf1hour" = ${AvgOf1hour}
            "avgOf8hours" = ${AvgOf8hours}
            "avgOfLatest" = ${AvgOfLatest}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to Statistics<PSCustomObject>

.DESCRIPTION

Convert from JSON to Statistics<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

Statistics<PSCustomObject>
#>
function ConvertFrom-JsonToStatistics {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => Statistics' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in Statistics
        $AllProperties = ("avgOf1day", "avgOf1hour", "avgOf8hours", "avgOfLatest")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "avgOf1day"))) { #optional property not found
            $AvgOf1day = $null
        } else {
            $AvgOf1day = $JsonParameters.PSobject.Properties["avgOf1day"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "avgOf1hour"))) { #optional property not found
            $AvgOf1hour = $null
        } else {
            $AvgOf1hour = $JsonParameters.PSobject.Properties["avgOf1hour"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "avgOf8hours"))) { #optional property not found
            $AvgOf8hours = $null
        } else {
            $AvgOf8hours = $JsonParameters.PSobject.Properties["avgOf8hours"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "avgOfLatest"))) { #optional property not found
            $AvgOfLatest = $null
        } else {
            $AvgOfLatest = $JsonParameters.PSobject.Properties["avgOfLatest"].value
        }

        $PSO = [PSCustomObject]@{
            "avgOf1day" = ${AvgOf1day}
            "avgOf1hour" = ${AvgOf1hour}
            "avgOf8hours" = ${AvgOf8hours}
            "avgOfLatest" = ${AvgOfLatest}
        }

        return $PSO
    }

}

