#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.5.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Items
No description available.
.OUTPUTS

ArcusSwitchDetailedFieldsSwitchPowerSupplies<PSCustomObject>
#>

function Initialize-ArcusSwitchDetailedFieldsSwitchPowerSupplies {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${Items}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => ArcusSwitchDetailedFieldsSwitchPowerSupplies' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "items" = ${Items}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ArcusSwitchDetailedFieldsSwitchPowerSupplies<PSCustomObject>

.DESCRIPTION

Convert from JSON to ArcusSwitchDetailedFieldsSwitchPowerSupplies<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ArcusSwitchDetailedFieldsSwitchPowerSupplies<PSCustomObject>
#>
function ConvertFrom-JsonToArcusSwitchDetailedFieldsSwitchPowerSupplies {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => ArcusSwitchDetailedFieldsSwitchPowerSupplies' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in ArcusSwitchDetailedFieldsSwitchPowerSupplies
        $AllProperties = ("items")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "items"))) { #optional property not found
            $Items = $null
        } else {
            $Items = $JsonParameters.PSobject.Properties["items"].value
        }

        $PSO = [PSCustomObject]@{
            "items" = ${Items}
        }

        return $PSO
    }

}

