#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.5.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

List of Shelves that requires activation.

.PARAMETER DrivesetList
List of driveset details.
.PARAMETER ShelfId
ID of shelf. A 42 digit hexadecimal number.
.OUTPUTS

NimbleShelfListDetails<PSCustomObject>
#>

function Initialize-NimbleShelfListDetails {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${DrivesetList},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${ShelfId}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => NimbleShelfListDetails' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $ShelfId) {
            throw "invalid value for 'ShelfId', 'ShelfId' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "driveset_list" = ${DrivesetList}
            "shelf_id" = ${ShelfId}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to NimbleShelfListDetails<PSCustomObject>

.DESCRIPTION

Convert from JSON to NimbleShelfListDetails<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

NimbleShelfListDetails<PSCustomObject>
#>
function ConvertFrom-JsonToNimbleShelfListDetails {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => NimbleShelfListDetails' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in NimbleShelfListDetails
        $AllProperties = ("driveset_list", "shelf_id")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'driveset_list' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "driveset_list"))) {
            throw "Error! JSON cannot be serialized due to the required property 'driveset_list' missing."
        } else {
            $DrivesetList = $JsonParameters.PSobject.Properties["driveset_list"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "shelf_id"))) {
            throw "Error! JSON cannot be serialized due to the required property 'shelf_id' missing."
        } else {
            $ShelfId = $JsonParameters.PSobject.Properties["shelf_id"].value
        }

        $PSO = [PSCustomObject]@{
            "driveset_list" = ${DrivesetList}
            "shelf_id" = ${ShelfId}
        }

        return $PSO
    }

}

