#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.5.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER ReplicationPartnerId
Replication Id of the parnter.
.PARAMETER Response
Task Response.
.PARAMETER Status
Task Status Status of the task.
.OUTPUTS

NimbleTestConfigurationResponse<PSCustomObject>
#>

function Initialize-NimbleTestConfigurationResponse {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${ReplicationPartnerId},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Response},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Status}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => NimbleTestConfigurationResponse' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "replication_partner_id" = ${ReplicationPartnerId}
            "response" = ${Response}
            "status" = ${Status}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to NimbleTestConfigurationResponse<PSCustomObject>

.DESCRIPTION

Convert from JSON to NimbleTestConfigurationResponse<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

NimbleTestConfigurationResponse<PSCustomObject>
#>
function ConvertFrom-JsonToNimbleTestConfigurationResponse {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => NimbleTestConfigurationResponse' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in NimbleTestConfigurationResponse
        $AllProperties = ("replication_partner_id", "response", "status")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "replication_partner_id"))) { #optional property not found
            $ReplicationPartnerId = $null
        } else {
            $ReplicationPartnerId = $JsonParameters.PSobject.Properties["replication_partner_id"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "response"))) { #optional property not found
            $Response = $null
        } else {
            $Response = $JsonParameters.PSobject.Properties["response"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "status"))) { #optional property not found
            $Status = $null
        } else {
            $Status = $JsonParameters.PSobject.Properties["status"].value
        }

        $PSO = [PSCustomObject]@{
            "replication_partner_id" = ${ReplicationPartnerId}
            "response" = ${Response}
            "status" = ${Status}
        }

        return $PSO
    }

}

