#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.5.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Fqn
Fully qualified name of folder.
.PARAMETER Id
Identifier of folder. A 42 digit hexadecimal number.
.OUTPUTS

NimbleFolderSummary<PSCustomObject>
#>

function Initialize-NimbleFolderSummary {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Fqn},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Id}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => NimbleFolderSummary' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "fqn" = ${Fqn}
            "id" = ${Id}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to NimbleFolderSummary<PSCustomObject>

.DESCRIPTION

Convert from JSON to NimbleFolderSummary<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

NimbleFolderSummary<PSCustomObject>
#>
function ConvertFrom-JsonToNimbleFolderSummary {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => NimbleFolderSummary' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in NimbleFolderSummary
        $AllProperties = ("fqn", "id")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "fqn"))) { #optional property not found
            $Fqn = $null
        } else {
            $Fqn = $JsonParameters.PSobject.Properties["fqn"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "id"))) { #optional property not found
            $Id = $null
        } else {
            $Id = $JsonParameters.PSobject.Properties["id"].value
        }

        $PSO = [PSCustomObject]@{
            "fqn" = ${Fqn}
            "id" = ${Id}
        }

        return $PSO
    }

}

