#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.3.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ExternalKeyManagerApi' {
    Context 'Invoke-DeviceType2CreateExternalKeyManager' {
        It 'Test Invoke-DeviceType2CreateExternalKeyManager' {
            #$TestResult = Invoke-DeviceType2CreateExternalKeyManager -SystemId "TEST_VALUE" -CreateExternalKeyManager "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-DeviceType2DeleteExternalKeyManagerById' {
        It 'Test Invoke-DeviceType2DeleteExternalKeyManagerById' {
            #$TestResult = Invoke-DeviceType2DeleteExternalKeyManagerById -SystemId "TEST_VALUE" -ExternalKeyManagerId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-DeviceType2EditExternalKeyManagerById' {
        It 'Test Invoke-DeviceType2EditExternalKeyManagerById' {
            #$TestResult = Invoke-DeviceType2EditExternalKeyManagerById -SystemId "TEST_VALUE" -ExternalKeyManagerId "TEST_VALUE" -EditExternalKeyManager "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-DeviceType2GetExternalKeyManager' {
        It 'Test Invoke-DeviceType2GetExternalKeyManager' {
            #$TestResult = Invoke-DeviceType2GetExternalKeyManager -SystemId "TEST_VALUE" -Select "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-DeviceType2GetExternalKeyManagerById' {
        It 'Test Invoke-DeviceType2GetExternalKeyManagerById' {
            #$TestResult = Invoke-DeviceType2GetExternalKeyManagerById -SystemId "TEST_VALUE" -ExternalKeyManagerId "TEST_VALUE" -Select "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-DeviceType2MigrateExternalKeyManagerById' {
        It 'Test Invoke-DeviceType2MigrateExternalKeyManagerById' {
            #$TestResult = Invoke-DeviceType2MigrateExternalKeyManagerById -SystemId "TEST_VALUE" -ExternalKeyManagerId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-DeviceType2RemoveExternalKeyManagerById' {
        It 'Test Invoke-DeviceType2RemoveExternalKeyManagerById' {
            #$TestResult = Invoke-DeviceType2RemoveExternalKeyManagerById -SystemId "TEST_VALUE" -ExternalKeyManagerId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
