#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.4.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER City
City of the installation site
.PARAMETER Company
Company name of the installation site
.PARAMETER Country
Country of the installation site
.PARAMETER HpePassportId
HPE passport ID
.PARAMETER HpePassword
Password of an HPE passport ID
.PARAMETER Id
Unique identifier of the installation site
.PARAMETER PostalCode
Postal code of the installation site
.PARAMETER SetSystemLocation
Apply system location to the system descriptor property
.PARAMETER State
State of the installation site
.PARAMETER StreetAddress
Street address of the installation site
.PARAMETER SupportProvider
Support provider of the installation site
.PARAMETER SystemId
SystemId/serialNumber of the array.
.OUTPUTS

ArcussystemSettingsDetailsInstallationsites<PSCustomObject>
#>

function Initialize-ArcussystemSettingsDetailsInstallationsites {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${City},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Company},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Country},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${HpePassportId},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${HpePassword},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Id},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${PostalCode},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${SetSystemLocation},
        [Parameter(Position = 8, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${State},
        [Parameter(Position = 9, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${StreetAddress},
        [Parameter(Position = 10, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${SupportProvider},
        [Parameter(Position = 11, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${SystemId}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => ArcussystemSettingsDetailsInstallationsites' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "city" = ${City}
            "company" = ${Company}
            "country" = ${Country}
            "hpePassportId" = ${HpePassportId}
            "hpePassword" = ${HpePassword}
            "id" = ${Id}
            "postalCode" = ${PostalCode}
            "setSystemLocation" = ${SetSystemLocation}
            "state" = ${State}
            "streetAddress" = ${StreetAddress}
            "supportProvider" = ${SupportProvider}
            "systemId" = ${SystemId}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ArcussystemSettingsDetailsInstallationsites<PSCustomObject>

.DESCRIPTION

Convert from JSON to ArcussystemSettingsDetailsInstallationsites<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ArcussystemSettingsDetailsInstallationsites<PSCustomObject>
#>
function ConvertFrom-JsonToArcussystemSettingsDetailsInstallationsites {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => ArcussystemSettingsDetailsInstallationsites' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in ArcussystemSettingsDetailsInstallationsites
        $AllProperties = ("city", "company", "country", "hpePassportId", "hpePassword", "id", "postalCode", "setSystemLocation", "state", "streetAddress", "supportProvider", "systemId")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "city"))) { #optional property not found
            $City = $null
        } else {
            $City = $JsonParameters.PSobject.Properties["city"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "company"))) { #optional property not found
            $Company = $null
        } else {
            $Company = $JsonParameters.PSobject.Properties["company"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "country"))) { #optional property not found
            $Country = $null
        } else {
            $Country = $JsonParameters.PSobject.Properties["country"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "hpePassportId"))) { #optional property not found
            $HpePassportId = $null
        } else {
            $HpePassportId = $JsonParameters.PSobject.Properties["hpePassportId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "hpePassword"))) { #optional property not found
            $HpePassword = $null
        } else {
            $HpePassword = $JsonParameters.PSobject.Properties["hpePassword"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "id"))) { #optional property not found
            $Id = $null
        } else {
            $Id = $JsonParameters.PSobject.Properties["id"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "postalCode"))) { #optional property not found
            $PostalCode = $null
        } else {
            $PostalCode = $JsonParameters.PSobject.Properties["postalCode"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "setSystemLocation"))) { #optional property not found
            $SetSystemLocation = $null
        } else {
            $SetSystemLocation = $JsonParameters.PSobject.Properties["setSystemLocation"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "state"))) { #optional property not found
            $State = $null
        } else {
            $State = $JsonParameters.PSobject.Properties["state"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "streetAddress"))) { #optional property not found
            $StreetAddress = $null
        } else {
            $StreetAddress = $JsonParameters.PSobject.Properties["streetAddress"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "supportProvider"))) { #optional property not found
            $SupportProvider = $null
        } else {
            $SupportProvider = $JsonParameters.PSobject.Properties["supportProvider"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "systemId"))) { #optional property not found
            $SystemId = $null
        } else {
            $SystemId = $JsonParameters.PSobject.Properties["systemId"].value
        }

        $PSO = [PSCustomObject]@{
            "city" = ${City}
            "company" = ${Company}
            "country" = ${Country}
            "hpePassportId" = ${HpePassportId}
            "hpePassword" = ${HpePassword}
            "id" = ${Id}
            "postalCode" = ${PostalCode}
            "setSystemLocation" = ${SetSystemLocation}
            "state" = ${State}
            "streetAddress" = ${StreetAddress}
            "supportProvider" = ${SupportProvider}
            "systemId" = ${SystemId}
        }

        return $PSO
    }

}

