#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.4.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER ArrayId
ID of array the disk belongs to. A 42 digit hexadecimal number. `Filter, Sort`
.PARAMETER ArrayName
Name of array the disk belongs to. String of up to 64 alphanumeric characters, - and . and : are allowed after first character.  `Filter, Sort`
.PARAMETER DeviceType
Type of disk (HDD, SSD, N/A). Disk type. Possible values: 'hdd', 'ssd'. `Filter, Sort`
.PARAMETER Id
Identifier of disk. A 42 digit hexadecimal number. `Filter`
.PARAMETER Model
Disk model name. `Filter, Sort`
.PARAMETER Serial
Disk serial number(N/A if empty). `Filter, Sort`
.PARAMETER ShelfId
Identifies the physical shelf the disk belongs to. A 42 digit hexadecimal number. `Filter, Sort`
.PARAMETER ShelfSerial
Serial number of the shelf the disk is attached to. `Filter, Sort`
.PARAMETER State
Disk hardware state. Disk state. Possible values: 'valid', 'in use', 'failed', absent', 'removed', 'void', 't_fail', 'foreign'. `Filter, Sort`
.OUTPUTS

DiskFilterableFields<PSCustomObject>
#>

function Initialize-DiskFilterableFields {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${ArrayId},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${ArrayName},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${DeviceType},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Id},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Model},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Serial},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${ShelfId},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${ShelfSerial},
        [Parameter(Position = 8, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${State}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => DiskFilterableFields' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "array_id" = ${ArrayId}
            "array_name" = ${ArrayName}
            "device_type" = ${DeviceType}
            "id" = ${Id}
            "model" = ${Model}
            "serial" = ${Serial}
            "shelf_id" = ${ShelfId}
            "shelf_serial" = ${ShelfSerial}
            "state" = ${State}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to DiskFilterableFields<PSCustomObject>

.DESCRIPTION

Convert from JSON to DiskFilterableFields<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

DiskFilterableFields<PSCustomObject>
#>
function ConvertFrom-JsonToDiskFilterableFields {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => DiskFilterableFields' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in DiskFilterableFields
        $AllProperties = ("array_id", "array_name", "device_type", "id", "model", "serial", "shelf_id", "shelf_serial", "state")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "array_id"))) { #optional property not found
            $ArrayId = $null
        } else {
            $ArrayId = $JsonParameters.PSobject.Properties["array_id"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "array_name"))) { #optional property not found
            $ArrayName = $null
        } else {
            $ArrayName = $JsonParameters.PSobject.Properties["array_name"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "device_type"))) { #optional property not found
            $DeviceType = $null
        } else {
            $DeviceType = $JsonParameters.PSobject.Properties["device_type"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "id"))) { #optional property not found
            $Id = $null
        } else {
            $Id = $JsonParameters.PSobject.Properties["id"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "model"))) { #optional property not found
            $Model = $null
        } else {
            $Model = $JsonParameters.PSobject.Properties["model"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "serial"))) { #optional property not found
            $Serial = $null
        } else {
            $Serial = $JsonParameters.PSobject.Properties["serial"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "shelf_id"))) { #optional property not found
            $ShelfId = $null
        } else {
            $ShelfId = $JsonParameters.PSobject.Properties["shelf_id"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "shelf_serial"))) { #optional property not found
            $ShelfSerial = $null
        } else {
            $ShelfSerial = $JsonParameters.PSobject.Properties["shelf_serial"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "state"))) { #optional property not found
            $State = $null
        } else {
            $State = $JsonParameters.PSobject.Properties["state"].value
        }

        $PSO = [PSCustomObject]@{
            "array_id" = ${ArrayId}
            "array_name" = ${ArrayName}
            "device_type" = ${DeviceType}
            "id" = ${Id}
            "model" = ${Model}
            "serial" = ${Serial}
            "shelf_id" = ${ShelfId}
            "shelf_serial" = ${ShelfSerial}
            "state" = ${State}
        }

        return $PSO
    }

}

