#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.3.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ArcusvlunsListSinglePortPos' {
    Context 'ArcusvlunsListSinglePortPos' {
        It 'Initialize-ArcusvlunsListSinglePortPos' {
            # a simple test to create an object
            #$NewObject = Initialize-ArcusvlunsListSinglePortPos -Node "TEST_VALUE" -Port "TEST_VALUE" -Slot "TEST_VALUE"
            #$NewObject | Should -BeOfType ArcusvlunsListSinglePortPos
            #$NewObject.property | Should -Be 0
        }
    }
}
