#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.3.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ArcusfilterDiskCapacity' {
    Context 'ArcusfilterDiskCapacity' {
        It 'Initialize-ArcusfilterDiskCapacity' {
            # a simple test to create an object
            #$NewObject = Initialize-ArcusfilterDiskCapacity -AllocatedMiB "TEST_VALUE" -FailedMiB "TEST_VALUE" -FreeMiB "TEST_VALUE" -TotalMiB "TEST_VALUE" -UnavailableMiB "TEST_VALUE"
            #$NewObject | Should -BeOfType ArcusfilterDiskCapacity
            #$NewObject.property | Should -Be 0
        }
    }
}
