#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.3.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ArcusKpiMetrics' {
    Context 'ArcusKpiMetrics' {
        It 'Initialize-ArcusKpiMetrics' {
            # a simple test to create an object
            #$NewObject = Initialize-ArcusKpiMetrics -Read "TEST_VALUE" -Total "TEST_VALUE" -Write "TEST_VALUE"
            #$NewObject | Should -BeOfType ArcusKpiMetrics
            #$NewObject.property | Should -Be 0
        }
    }
}
