#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.3.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ArcusperformanceHistoryData' {
    Context 'ArcusperformanceHistoryData' {
        It 'Initialize-ArcusperformanceHistoryData' {
            # a simple test to create an object
            #$NewObject = Initialize-ArcusperformanceHistoryData -CustomerId "TEST_VALUE" -EndTime "TEST_VALUE" -HistoryData "TEST_VALUE" -RequestUri "TEST_VALUE" -StartTime "TEST_VALUE"
            #$NewObject | Should -BeOfType ArcusperformanceHistoryData
            #$NewObject.property | Should -Be 0
        }
    }
}
