#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.3.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'DeviceTypes' {
    Context 'DeviceTypes' {
        It 'Initialize-DeviceTypes' {
            # a simple test to create an object
            #$NewObject = Initialize-DeviceTypes -Description "TEST_VALUE" -DeviceType "TEST_VALUE"
            #$NewObject | Should -BeOfType DeviceTypes
            #$NewObject.property | Should -Be 0
        }
    }
}
