#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.3.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'EditSnmpSettings' {
    Context 'EditSnmpSettings' {
        It 'Initialize-EditSnmpSettings' {
            # a simple test to create an object
            #$NewObject = Initialize-EditSnmpSettings -SnmpCommunity "TEST_VALUE" -SnmpGetEnabled "TEST_VALUE" -SnmpGetPort "TEST_VALUE" -SnmpSysContact "TEST_VALUE" -SnmpSysLocation "TEST_VALUE" -SnmpTrapEnabled "TEST_VALUE" -SnmpTrapHost "TEST_VALUE" -SnmpTrapPort "TEST_VALUE"
            #$NewObject | Should -BeOfType EditSnmpSettings
            #$NewObject.property | Should -Be 0
        }
    }
}
