#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.3.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'NimbleKpiMetrics' {
    Context 'NimbleKpiMetrics' {
        It 'Initialize-NimbleKpiMetrics' {
            # a simple test to create an object
            #$NewObject = Initialize-NimbleKpiMetrics -Read "TEST_VALUE" -Total "TEST_VALUE" -Write "TEST_VALUE"
            #$NewObject | Should -BeOfType NimbleKpiMetrics
            #$NewObject.property | Should -Be 0
        }
    }
}
