#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.3.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'NimbleEditFCInterfaceInput' {
    Context 'NimbleEditFCInterfaceInput' {
        It 'Initialize-NimbleEditFCInterfaceInput' {
            # a simple test to create an object
            #$NewObject = Initialize-NimbleEditFCInterfaceInput -Online "TEST_VALUE"
            #$NewObject | Should -BeOfType NimbleEditFCInterfaceInput
            #$NewObject.property | Should -Be 0
        }
    }
}
