#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.3.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'NimbleDriveSetDetails' {
    Context 'NimbleDriveSetDetails' {
        It 'Initialize-NimbleDriveSetDetails' {
            # a simple test to create an object
            #$NewObject = Initialize-NimbleDriveSetDetails -AcceptDedupeImpact "TEST_VALUE" -AcceptForeign "TEST_VALUE" -Driveset "TEST_VALUE"
            #$NewObject | Should -BeOfType NimbleDriveSetDetails
            #$NewObject.property | Should -Be 0
        }
    }
}
