#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.3.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'WitnessFilterableFieldsWithoutFilter' {
    Context 'WitnessFilterableFieldsWithoutFilter' {
        It 'Initialize-WitnessFilterableFieldsWithoutFilter' {
            # a simple test to create an object
            #$NewObject = Initialize-WitnessFilterableFieldsWithoutFilter -Id "TEST_VALUE"
            #$NewObject | Should -BeOfType WitnessFilterableFieldsWithoutFilter
            #$NewObject.property | Should -Be 0
        }
    }
}
