#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.4.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ArcusvcenterSettingDetail' {
    Context 'ArcusvcenterSettingDetail' {
        It 'Initialize-ArcusvcenterSettingDetail' {
            # a simple test to create an object
            #$NewObject = Initialize-ArcusvcenterSettingDetail -ConsoleUri "TEST_VALUE" -CustomerId "TEST_VALUE" -Description "TEST_VALUE" -FriendlyCert "TEST_VALUE" -Generation "TEST_VALUE" -Id "TEST_VALUE" -Inetaddress "TEST_VALUE" -Name "TEST_VALUE" -Port "TEST_VALUE" -RequestUri "TEST_VALUE" -ResourceUri "TEST_VALUE" -Status "TEST_VALUE" -SystemId "TEST_VALUE" -Type "TEST_VALUE" -Username "TEST_VALUE" -VmManagerType "TEST_VALUE"
            #$NewObject | Should -BeOfType ArcusvcenterSettingDetail
            #$NewObject.property | Should -Be 0
        }
    }
}
