#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.4.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ArcusProtectionPolicyPolicySecondaryRemote' {
    Context 'ArcusProtectionPolicyPolicySecondaryRemote' {
        It 'Initialize-ArcusProtectionPolicyPolicySecondaryRemote' {
            # a simple test to create an object
            #$NewObject = Initialize-ArcusProtectionPolicyPolicySecondaryRemote -CustomerId "TEST_VALUE" -IsRemoteArraySupportReplication "TEST_VALUE" -PartnerId "TEST_VALUE" -PartnerName "TEST_VALUE" -ReplicationType "TEST_VALUE" -ResourceUri "TEST_VALUE"
            #$NewObject | Should -BeOfType ArcusProtectionPolicyPolicySecondaryRemote
            #$NewObject.property | Should -Be 0
        }
    }
}
