#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.4.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ArcusDiskCapacity' {
    Context 'ArcusDiskCapacity' {
        It 'Initialize-ArcusDiskCapacity' {
            # a simple test to create an object
            #$NewObject = Initialize-ArcusDiskCapacity -AllocatedMiB "TEST_VALUE" -FailedMiB "TEST_VALUE" -FreeMiB "TEST_VALUE" -TotalMiB "TEST_VALUE" -UnavailableMiB "TEST_VALUE"
            #$NewObject | Should -BeOfType ArcusDiskCapacity
            #$NewObject.property | Should -Be 0
        }
    }
}
