#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.4.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ArcusRemoveProtectionPolicyInputSchema' {
    Context 'ArcusRemoveProtectionPolicyInputSchema' {
        It 'Initialize-ArcusRemoveProtectionPolicyInputSchema' {
            # a simple test to create an object
            #$NewObject = Initialize-ArcusRemoveProtectionPolicyInputSchema -Remote "TEST_VALUE" -RemoveOnlySchedules "TEST_VALUE" -RemoveSchedules "TEST_VALUE" -SecondaryRemote "TEST_VALUE"
            #$NewObject | Should -BeOfType ArcusRemoveProtectionPolicyInputSchema
            #$NewObject.property | Should -Be 0
        }
    }
}
