#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.4.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'DisksList' {
    Context 'DisksList' {
        It 'Initialize-DisksList' {
            # a simple test to create an object
            #$NewObject = Initialize-DisksList -AdmitTime "TEST_VALUE" -Capacity "TEST_VALUE" -ConsumableSizeMiB "TEST_VALUE" -CustomerId "TEST_VALUE" -DevType "TEST_VALUE" -DiskId "TEST_VALUE" -Displayname "TEST_VALUE" -Domain "TEST_VALUE" -FwStatus "TEST_VALUE" -FwVersion "TEST_VALUE" -Generation "TEST_VALUE" -Id "TEST_VALUE" -LifeLeftPCT "TEST_VALUE" -LoopA0 "TEST_VALUE" -LoopA1 "TEST_VALUE" -LoopB0 "TEST_VALUE" -LoopB1 "TEST_VALUE" -Manufacturing "TEST_VALUE" -MediaType "TEST_VALUE" -MfgCapacityGB "TEST_VALUE" -PositionLast "TEST_VALUE" -PositionNow "TEST_VALUE" -Protocol "TEST_VALUE" -RawSizeMiB "TEST_VALUE" -ReadErrors "TEST_VALUE" -ResourceUri "TEST_VALUE" -SedStatus "TEST_VALUE" -Speed "TEST_VALUE" -State "TEST_VALUE" -SystemId "TEST_VALUE" -TempMax "TEST_VALUE" -TempMin "TEST_VALUE" -TempNow "TEST_VALUE" -Type "TEST_VALUE" -WriteErrors "TEST_VALUE" -Wwn "TEST_VALUE"
            #$NewObject | Should -BeOfType DisksList
            #$NewObject.property | Should -Be 0
        }
    }
}
