#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.4.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'EditEnclosureInput' {
    Context 'EditEnclosureInput' {
        It 'Initialize-EditEnclosureInput' {
            # a simple test to create an object
            #$NewObject = Initialize-EditEnclosureInput -Id "TEST_VALUE" -Location "TEST_VALUE"
            #$NewObject | Should -BeOfType EditEnclosureInput
            #$NewObject.property | Should -Be 0
        }
    }
}
