#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.4.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'EditAlertSettings' {
    Context 'EditAlertSettings' {
        It 'Initialize-EditAlertSettings' {
            # a simple test to create an object
            #$NewObject = Initialize-EditAlertSettings -AlertFromEmailAddr "TEST_VALUE" -AlertMinLevel "TEST_VALUE" -AlertToEmailAddrs "TEST_VALUE" -SendAlertToSupport "TEST_VALUE"
            #$NewObject | Should -BeOfType EditAlertSettings
            #$NewObject.property | Should -Be 0
        }
    }
}
