#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.4.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'FcPortSfp' {
    Context 'FcPortSfp' {
        It 'Initialize-FcPortSfp' {
            # a simple test to create an object
            #$NewObject = Initialize-FcPortSfp -FwVersion "TEST_VALUE" -Manufacturing "TEST_VALUE" -Name "TEST_VALUE" -Qualified "TEST_VALUE" -RxLossPin "TEST_VALUE" -RxPowerLow "TEST_VALUE" -Speed "TEST_VALUE" -State "TEST_VALUE" -TxDisablePin "TEST_VALUE" -TxFaultPin "TEST_VALUE"
            #$NewObject | Should -BeOfType FcPortSfp
            #$NewObject.property | Should -Be 0
        }
    }
}
