#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.4.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'FleetVolumeset' {
    Context 'FleetVolumeset' {
        It 'Initialize-FleetVolumeset' {
            # a simple test to create an object
            #$NewObject = Initialize-FleetVolumeset -AppType "TEST_VALUE" -Application "TEST_VALUE" -AssociatedLinks "TEST_VALUE" -CustomerId "TEST_VALUE" -Generation "TEST_VALUE" -Id "TEST_VALUE" -Members "TEST_VALUE" -Name "TEST_VALUE" -ProductFamily "TEST_VALUE" -ResourceUri "TEST_VALUE" -SystemId "TEST_VALUE" -Type "TEST_VALUE"
            #$NewObject | Should -BeOfType FleetVolumeset
            #$NewObject.property | Should -Be 0
        }
    }
}
