#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.4.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'HotspotMetricsPerCategory' {
    Context 'HotspotMetricsPerCategory' {
        It 'Initialize-HotspotMetricsPerCategory' {
            # a simple test to create an object
            #$NewObject = Initialize-HotspotMetricsPerCategory -Read "TEST_VALUE" -Write "TEST_VALUE"
            #$NewObject | Should -BeOfType HotspotMetricsPerCategory
            #$NewObject.property | Should -Be 0
        }
    }
}
