#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.4.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'LED' {
    Context 'LED' {
        It 'Initialize-LED' {
            # a simple test to create an object
            #$NewObject = Initialize-LED
            #$NewObject | Should -BeOfType LED
            #$NewObject.property | Should -Be 0
        }
    }
}
