#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.4.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'NimbleCreateVolumeCollectionInput' {
    Context 'NimbleCreateVolumeCollectionInput' {
        It 'Initialize-NimbleCreateVolumeCollectionInput' {
            # a simple test to create an object
            #$NewObject = Initialize-NimbleCreateVolumeCollectionInput -AgentHostname "TEST_VALUE" -AgentUsername "TEST_VALUE" -AppClusterName "TEST_VALUE" -AppId "TEST_VALUE" -AppServer "TEST_VALUE" -AppServiceName "TEST_VALUE" -AppSync "TEST_VALUE" -Description "TEST_VALUE" -IsStandaloneVolcoll "TEST_VALUE" -Metadata "TEST_VALUE" -Name "TEST_VALUE" -ProttmplId "TEST_VALUE" -ReplicationType "TEST_VALUE" -VcenterHostname "TEST_VALUE" -VcenterUsername "TEST_VALUE" -VolumeList "TEST_VALUE"
            #$NewObject | Should -BeOfType NimbleCreateVolumeCollectionInput
            #$NewObject.property | Should -Be 0
        }
    }
}
