#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.4.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'NodeMcusSummaryList' {
    Context 'NodeMcusSummaryList' {
        It 'Initialize-NodeMcusSummaryList' {
            # a simple test to create an object
            #$NewObject = Initialize-NodeMcusSummaryList -Items "TEST_VALUE" -PageLimit "TEST_VALUE" -PageOffset "TEST_VALUE" -RequestUri "TEST_VALUE" -Total "TEST_VALUE"
            #$NewObject | Should -BeOfType NodeMcusSummaryList
            #$NewObject.property | Should -Be 0
        }
    }
}
