#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.5.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ArcusSwitchOverParams' {
    Context 'ArcusSwitchOverParams' {
        It 'Initialize-ArcusSwitchOverParams' {
            # a simple test to create an object
            #$NewObject = Initialize-ArcusSwitchOverParams -NoSnapshot "TEST_VALUE" -TargetName "TEST_VALUE"
            #$NewObject | Should -BeOfType ArcusSwitchOverParams
            #$NewObject.property | Should -Be 0
        }
    }
}
