#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.5.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ArcuscertificatesList' {
    Context 'ArcuscertificatesList' {
        It 'Initialize-ArcuscertificatesList' {
            # a simple test to create an object
            #$NewObject = Initialize-ArcuscertificatesList -AssociatedLinks "TEST_VALUE" -CertType "TEST_VALUE" -Commonname "TEST_VALUE" -ConsoleUri "TEST_VALUE" -CustomerId "TEST_VALUE" -Displayname "TEST_VALUE" -Domain "TEST_VALUE" -Enddate "TEST_VALUE" -Fingerprint "TEST_VALUE" -Generation "TEST_VALUE" -Id "TEST_VALUE" -Issuer "TEST_VALUE" -Pem "TEST_VALUE" -Serial "TEST_VALUE" -Service "TEST_VALUE" -Signaturetype "TEST_VALUE" -Startdate "TEST_VALUE" -Subject "TEST_VALUE" -Subjectaltname "TEST_VALUE" -SystemId "TEST_VALUE" -Text "TEST_VALUE" -Type "TEST_VALUE" -Uri "TEST_VALUE"
            #$NewObject | Should -BeOfType ArcuscertificatesList
            #$NewObject.property | Should -Be 0
        }
    }
}
