#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.5.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ArcussnapshotsetsList' {
    Context 'ArcussnapshotsetsList' {
        It 'Initialize-ArcussnapshotsetsList' {
            # a simple test to create an object
            #$NewObject = Initialize-ArcussnapshotsetsList -AppSetBusinessUnit "TEST_VALUE" -AppSetComments "TEST_VALUE" -AppSetExcludeAIQoS "TEST_VALUE" -AppSetImportance "TEST_VALUE" -AppSetName "TEST_VALUE" -AppSetType "TEST_VALUE" -Comment "TEST_VALUE" -CreationTime "TEST_VALUE" -CustomerId "TEST_VALUE" -DisplayName "TEST_VALUE" -Domain "TEST_VALUE" -ExportStatus "TEST_VALUE" -Generation "TEST_VALUE" -Id "TEST_VALUE" -KvPairsPresent "TEST_VALUE" -Members "TEST_VALUE" -Name "TEST_VALUE" -RequestUri "TEST_VALUE" -SerialNumber "TEST_VALUE" -SnapSetId "TEST_VALUE" -SnapSetParentId "TEST_VALUE" -SnapSetParentName "TEST_VALUE" -SystemId "TEST_VALUE" -Type "TEST_VALUE" -VvSetType "TEST_VALUE"
            #$NewObject | Should -BeOfType ArcussnapshotsetsList
            #$NewObject.property | Should -Be 0
        }
    }
}
