#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.5.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ArcusnetworkServicesSnmp' {
    Context 'ArcusnetworkServicesSnmp' {
        It 'Initialize-ArcusnetworkServicesSnmp' {
            # a simple test to create an object
            #$NewObject = Initialize-ArcusnetworkServicesSnmp -Items "TEST_VALUE" -RequestUri "TEST_VALUE"
            #$NewObject | Should -BeOfType ArcusnetworkServicesSnmp
            #$NewObject.property | Should -Be 0
        }
    }
}
