#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.5.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ArcusSystemLatencyFactorsLatencyBandsReadInner' {
    Context 'ArcusSystemLatencyFactorsLatencyBandsReadInner' {
        It 'Initialize-ArcusSystemLatencyFactorsLatencyBandsReadInner' {
            # a simple test to create an object
            #$NewObject = Initialize-ArcusSystemLatencyFactorsLatencyBandsReadInner -EndTime "TEST_VALUE" -StartTime "TEST_VALUE" -TopFactors "TEST_VALUE"
            #$NewObject | Should -BeOfType ArcusSystemLatencyFactorsLatencyBandsReadInner
            #$NewObject.property | Should -Be 0
        }
    }
}
