#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.5.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ArcusenclosureCardPciDetails' {
    Context 'ArcusenclosureCardPciDetails' {
        It 'Initialize-ArcusenclosureCardPciDetails' {
            # a simple test to create an object
            #$NewObject = Initialize-ArcusenclosureCardPciDetails -CustomerId "TEST_VALUE" -Displayname "TEST_VALUE" -Domain "TEST_VALUE" -EnclosureCardId "TEST_VALUE" -EnclosureCardUid "TEST_VALUE" -EnclosureId "TEST_VALUE" -EnclosureUid "TEST_VALUE" -FwVersion "TEST_VALUE" -Generation "TEST_VALUE" -Id "TEST_VALUE" -Manufacturing "TEST_VALUE" -PortCount "TEST_VALUE" -Revision "TEST_VALUE" -Slot "TEST_VALUE" -SystemId "TEST_VALUE" -Type "TEST_VALUE"
            #$NewObject | Should -BeOfType ArcusenclosureCardPciDetails
            #$NewObject.property | Should -Be 0
        }
    }
}
