#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.5.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ArcusPortNVMe' {
    Context 'ArcusPortNVMe' {
        It 'Initialize-ArcusPortNVMe' {
            # a simple test to create an object
            #$NewObject = Initialize-ArcusPortNVMe -DelimitedMacAddress "TEST_VALUE" -Eth "TEST_VALUE" -GatewayAddress "TEST_VALUE" -IpAddress "TEST_VALUE" -MacAddress "TEST_VALUE" -Mode "TEST_VALUE" -Mtu "TEST_VALUE" -Nqn "TEST_VALUE" -Pcidev "TEST_VALUE" -PrefixLength "TEST_VALUE" -Protocol "TEST_VALUE" -Rate "TEST_VALUE" -State "TEST_VALUE" -VlanCount "TEST_VALUE" -Vlans "TEST_VALUE"
            #$NewObject | Should -BeOfType ArcusPortNVMe
            #$NewObject.property | Should -Be 0
        }
    }
}
