#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.5.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ArcusProtectionPoliciesListAssociatedLinksInner' {
    Context 'ArcusProtectionPoliciesListAssociatedLinksInner' {
        It 'Initialize-ArcusProtectionPoliciesListAssociatedLinksInner' {
            # a simple test to create an object
            #$NewObject = Initialize-ArcusProtectionPoliciesListAssociatedLinksInner -ResourceUri "TEST_VALUE" -Type "TEST_VALUE"
            #$NewObject | Should -BeOfType ArcusProtectionPoliciesListAssociatedLinksInner
            #$NewObject.property | Should -Be 0
        }
    }
}
