#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.5.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ArrayMigStatus' {
    Context 'ArrayMigStatus' {
        It 'Initialize-ArrayMigStatus' {
            # a simple test to create an object
            #$NewObject = Initialize-ArrayMigStatus -Id "TEST_VALUE" -IsDataSource "TEST_VALUE" -Name "TEST_VALUE" -SpaceUtilization "TEST_VALUE"
            #$NewObject | Should -BeOfType ArrayMigStatus
            #$NewObject.property | Should -Be 0
        }
    }
}
