#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.5.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'AuditBadRequest' {
    Context 'AuditBadRequest' {
        It 'Initialize-AuditBadRequest' {
            # a simple test to create an object
            #$NewObject = Initialize-AuditBadRequest -ErrorCode "TEST_VALUE" -VarError "TEST_VALUE" -TraceId "TEST_VALUE"
            #$NewObject | Should -BeOfType AuditBadRequest
            #$NewObject.property | Should -Be 0
        }
    }
}
