#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.5.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'CpgAlert' {
    Context 'CpgAlert' {
        It 'Initialize-CpgAlert' {
            # a simple test to create an object
            #$NewObject = Initialize-CpgAlert -Fail "TEST_VALUE" -Limit "TEST_VALUE" -Warn "TEST_VALUE" -WarnPercent "TEST_VALUE"
            #$NewObject | Should -BeOfType CpgAlert
            #$NewObject.property | Should -Be 0
        }
    }
}
