#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.5.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'CreateHostInput' {
    Context 'CreateHostInput' {
        It 'Initialize-CreateHostInput' {
            # a simple test to create an object
            #$NewObject = Initialize-CreateHostInput -Comment "TEST_VALUE" -Contact "TEST_VALUE" -Fqdn "TEST_VALUE" -HostGroupIds "TEST_VALUE" -InitiatorIds "TEST_VALUE" -InitiatorsToCreate "TEST_VALUE" -IpAddress "TEST_VALUE" -Location "TEST_VALUE" -Model "TEST_VALUE" -Name "TEST_VALUE" -OperatingSystem "TEST_VALUE" -Persona "TEST_VALUE" -Protocol "TEST_VALUE" -Subnet "TEST_VALUE" -UserCreated "TEST_VALUE"
            #$NewObject | Should -BeOfType CreateHostInput
            #$NewObject.property | Should -Be 0
        }
    }
}
