#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.5.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'EcDcsdata' {
    Context 'EcDcsdata' {
        It 'Initialize-EcDcsdata' {
            # a simple test to create an object
            #$NewObject = Initialize-EcDcsdata -FwStatus "TEST_VALUE" -FwVersion "TEST_VALUE" -Master "TEST_VALUE" -SasStatus "TEST_VALUE"
            #$NewObject | Should -BeOfType EcDcsdata
            #$NewObject.property | Should -Be 0
        }
    }
}
