#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.5.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'EnclosuresDetails' {
    Context 'EnclosuresDetails' {
        It 'Initialize-EnclosuresDetails' {
            # a simple test to create an object
            #$NewObject = Initialize-EnclosuresDetails -AssociatedLinks "TEST_VALUE" -ChainPosLoopA "TEST_VALUE" -ChainPosLoopB "TEST_VALUE" -ConsoleUri "TEST_VALUE" -CustomerId "TEST_VALUE" -Dc4data "TEST_VALUE" -Dcsdata "TEST_VALUE" -DetailedState "TEST_VALUE" -Displayname "TEST_VALUE" -Domain "TEST_VALUE" -EnclosureId "TEST_VALUE" -EnclosureType "TEST_VALUE" -Errors "TEST_VALUE" -FailIndicator "TEST_VALUE" -FailRequested "TEST_VALUE" -FormFactor "TEST_VALUE" -Generation "TEST_VALUE" -Id "TEST_VALUE" -LocateEnabled "TEST_VALUE" -Location "TEST_VALUE" -LoopSplit "TEST_VALUE" -Manufacturing "TEST_VALUE" -Name "TEST_VALUE" -NodeWwn "TEST_VALUE" -RequestUri "TEST_VALUE" -ResourceUri "TEST_VALUE" -State "TEST_VALUE" -SubType "TEST_VALUE" -SystemId "TEST_VALUE" -Type "TEST_VALUE" -WarnIndicator "TEST_VALUE" -WarnRequested "TEST_VALUE"
            #$NewObject | Should -BeOfType EnclosuresDetails
            #$NewObject.property | Should -Be 0
        }
    }
}
