#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.5.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'FieldsWithoutFilter' {
    Context 'FieldsWithoutFilter' {
        It 'Initialize-FieldsWithoutFilter' {
            # a simple test to create an object
            #$NewObject = Initialize-FieldsWithoutFilter -Hostname "TEST_VALUE" -Id "TEST_VALUE" -Name "TEST_VALUE" -ServerType "TEST_VALUE"
            #$NewObject | Should -BeOfType FieldsWithoutFilter
            #$NewObject.property | Should -Be 0
        }
    }
}
