#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.5.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'FleetVolumeSetList' {
    Context 'FleetVolumeSetList' {
        It 'Initialize-FleetVolumeSetList' {
            # a simple test to create an object
            #$NewObject = Initialize-FleetVolumeSetList -Items "TEST_VALUE" -PageLimit "TEST_VALUE" -PageOffset "TEST_VALUE" -RequestUri "TEST_VALUE" -Total "TEST_VALUE"
            #$NewObject | Should -BeOfType FleetVolumeSetList
            #$NewObject.property | Should -Be 0
        }
    }
}
