#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.5.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'NimbleMergeGroupsInput' {
    Context 'NimbleMergeGroupsInput' {
        It 'Initialize-NimbleMergeGroupsInput' {
            # a simple test to create an object
            #$NewObject = Initialize-NimbleMergeGroupsInput -Force "TEST_VALUE" -SkipSecondaryMgmtIp "TEST_VALUE" -SrcGroupIp "TEST_VALUE" -SrcGroupName "TEST_VALUE" -SrcPassphrase "TEST_VALUE" -SrcPassword "TEST_VALUE" -SrcUsername "TEST_VALUE"
            #$NewObject | Should -BeOfType NimbleMergeGroupsInput
            #$NewObject.property | Should -Be 0
        }
    }
}
