#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.5.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'NimbleVolumeSummary' {
    Context 'NimbleVolumeSummary' {
        It 'Initialize-NimbleVolumeSummary' {
            # a simple test to create an object
            #$NewObject = Initialize-NimbleVolumeSummary -AgentType "TEST_VALUE" -Id "TEST_VALUE" -Name "TEST_VALUE" -VolId "TEST_VALUE" -VolName "TEST_VALUE" -VolumeCreatorId "TEST_VALUE" -VolumeCreatorName "TEST_VALUE"
            #$NewObject | Should -BeOfType NimbleVolumeSummary
            #$NewObject.property | Should -Be 0
        }
    }
}
