#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.5.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'NimbleAlarmsFieldsWithoutSortKey' {
    Context 'NimbleAlarmsFieldsWithoutSortKey' {
        It 'Initialize-NimbleAlarmsFieldsWithoutSortKey' {
            # a simple test to create an object
            #$NewObject = Initialize-NimbleAlarmsFieldsWithoutSortKey -AckTime "TEST_VALUE" -Activity "TEST_VALUE" -AlarmType "TEST_VALUE" -Array "TEST_VALUE" -Category "TEST_VALUE" -CurrOnsetEventId "TEST_VALUE" -Id "TEST_VALUE" -NextNotificationTime "TEST_VALUE" -ObjectId "TEST_VALUE" -ObjectName "TEST_VALUE" -ObjectType "TEST_VALUE" -OnsetTime "TEST_VALUE" -RemindEvery "TEST_VALUE" -RemindEveryUnit "TEST_VALUE" -Severity "TEST_VALUE" -Status "TEST_VALUE" -UserFullName "TEST_VALUE" -UserId "TEST_VALUE" -UserName "TEST_VALUE"
            #$NewObject | Should -BeOfType NimbleAlarmsFieldsWithoutSortKey
            #$NewObject.property | Should -Be 0
        }
    }
}
