#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.5.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'NimbleFCConfigsList' {
    Context 'NimbleFCConfigsList' {
        It 'Initialize-NimbleFCConfigsList' {
            # a simple test to create an object
            #$NewObject = Initialize-NimbleFCConfigsList -Items "TEST_VALUE" -PageLimit "TEST_VALUE" -PageOffset "TEST_VALUE" -RequestUri "TEST_VALUE" -Total "TEST_VALUE"
            #$NewObject | Should -BeOfType NimbleFCConfigsList
            #$NewObject.property | Should -Be 0
        }
    }
}
