#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.5.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'NimbleNsCtrlrNvmeCard' {
    Context 'NimbleNsCtrlrNvmeCard' {
        It 'Initialize-NimbleNsCtrlrNvmeCard' {
            # a simple test to create an object
            #$NewObject = Initialize-NimbleNsCtrlrNvmeCard -SerialNumber "TEST_VALUE" -Size "TEST_VALUE" -State "TEST_VALUE"
            #$NewObject | Should -BeOfType NimbleNsCtrlrNvmeCard
            #$NewObject.property | Should -Be 0
        }
    }
}
