#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.5.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'NimbleStorageSystemFieldsWithSortKey' {
    Context 'NimbleStorageSystemFieldsWithSortKey' {
        It 'Initialize-NimbleStorageSystemFieldsWithSortKey' {
            # a simple test to create an object
            #$NewObject = Initialize-NimbleStorageSystemFieldsWithSortKey -Id "TEST_VALUE" -Name "TEST_VALUE"
            #$NewObject | Should -BeOfType NimbleStorageSystemFieldsWithSortKey
            #$NewObject.property | Should -Be 0
        }
    }
}
