#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.5.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'NimblePoolFieldsWithSortKey' {
    Context 'NimblePoolFieldsWithSortKey' {
        It 'Initialize-NimblePoolFieldsWithSortKey' {
            # a simple test to create an object
            #$NewObject = Initialize-NimblePoolFieldsWithSortKey -Id "TEST_VALUE" -Name "TEST_VALUE"
            #$NewObject | Should -BeOfType NimblePoolFieldsWithSortKey
            #$NewObject.property | Should -Be 0
        }
    }
}
