#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.5.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'PortPosition' {
    Context 'PortPosition' {
        It 'Initialize-PortPosition' {
            # a simple test to create an object
            #$NewObject = Initialize-PortPosition -Node "TEST_VALUE" -Port "TEST_VALUE" -Slot "TEST_VALUE"
            #$NewObject | Should -BeOfType PortPosition
            #$NewObject.property | Should -Be 0
        }
    }
}
