#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.5.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'PrimeraProtectionPolicyInputSchema' {
    Context 'PrimeraProtectionPolicyInputSchema' {
        It 'Initialize-PrimeraProtectionPolicyInputSchema' {
            # a simple test to create an object
            #$NewObject = Initialize-PrimeraProtectionPolicyInputSchema -AutoRecover "TEST_VALUE" -AutoSynchronize "TEST_VALUE" -NoAutomaticSynchronization "TEST_VALUE" -NonZeroRtoConfig "TEST_VALUE" -OverPeriodAlert "TEST_VALUE" -Remote "TEST_VALUE" -RpoSecs "TEST_VALUE" -SecondaryRemote "TEST_VALUE" -ZeroRtoConfig "TEST_VALUE"
            #$NewObject | Should -BeOfType PrimeraProtectionPolicyInputSchema
            #$NewObject.property | Should -Be 0
        }
    }
}
