#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.5.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ReverseParams' {
    Context 'ReverseParams' {
        It 'Initialize-ReverseParams' {
            # a simple test to create an object
            #$NewObject = Initialize-ReverseParams -Current "TEST_VALUE" -LocalGroupDirection "TEST_VALUE" -Natural "TEST_VALUE" -NoSnapshot "TEST_VALUE" -SkipPromote "TEST_VALUE" -StopGroups "TEST_VALUE" -TargetName "TEST_VALUE"
            #$NewObject | Should -BeOfType ReverseParams
            #$NewObject.property | Should -Be 0
        }
    }
}
