#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.5.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'SysLocateInput' {
    Context 'SysLocateInput' {
        It 'Initialize-SysLocateInput' {
            # a simple test to create an object
            #$NewObject = Initialize-SysLocateInput -LocateEnabled "TEST_VALUE"
            #$NewObject | Should -BeOfType SysLocateInput
            #$NewObject.property | Should -Be 0
        }
    }
}
