#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.5.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'TasksServiceUnavailable' {
    Context 'TasksServiceUnavailable' {
        It 'Initialize-TasksServiceUnavailable' {
            # a simple test to create an object
            #$NewObject = Initialize-TasksServiceUnavailable -ErrorCode "TEST_VALUE" -VarError "TEST_VALUE" -TraceId "TEST_VALUE"
            #$NewObject | Should -BeOfType TasksServiceUnavailable
            #$NewObject.property | Should -Be 0
        }
    }
}
