#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.5.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'VasaServiceConfig' {
    Context 'VasaServiceConfig' {
        It 'Initialize-VasaServiceConfig' {
            # a simple test to create an object
            #$NewObject = Initialize-VasaServiceConfig -CertMgmt "TEST_VALUE" -VasaStateEnabled "TEST_VALUE"
            #$NewObject | Should -BeOfType VasaServiceConfig
            #$NewObject.property | Should -Be 0
        }
    }
}
