#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.4.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ArcusfriendlyCert' {
    Context 'ArcusfriendlyCert' {
        It 'Initialize-ArcusfriendlyCert' {
            # a simple test to create an object
            #$NewObject = Initialize-ArcusfriendlyCert -ValidFrom "TEST_VALUE" -ValidUntil "TEST_VALUE" -IssuedTo "TEST_VALUE" -Issuer "TEST_VALUE"
            #$NewObject | Should -BeOfType ArcusfriendlyCert
            #$NewObject.property | Should -Be 0
        }
    }
}
