#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.4.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ArcusSchedule' {
    Context 'ArcusSchedule' {
        It 'Initialize-ArcusSchedule' {
            # a simple test to create an object
            #$NewObject = Initialize-ArcusSchedule -AtTime "TEST_VALUE" -CustomerId "TEST_VALUE" -Days "TEST_VALUE" -DaysOfMonth "TEST_VALUE" -ExpireSecs "TEST_VALUE" -Generation "TEST_VALUE" -Id "TEST_VALUE" -IsAlertEnabled "TEST_VALUE" -IsPaused "TEST_VALUE" -IsRemote "TEST_VALUE" -IsSystemTask "TEST_VALUE" -Name "TEST_VALUE" -NextRunTime "TEST_VALUE" -Period "TEST_VALUE" -PeriodUnit "TEST_VALUE" -RetainSecs "TEST_VALUE" -Status "TEST_VALUE" -SystemWwn "TEST_VALUE" -Type "TEST_VALUE" -UntilTime "TEST_VALUE" -User "TEST_VALUE"
            #$NewObject | Should -BeOfType ArcusSchedule
            #$NewObject.property | Should -Be 0
        }
    }
}
