#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.4.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'CreateProtectionPolicyInputSchema' {
    Context 'CreateProtectionPolicyInputSchema' {
        It 'Initialize-CreateProtectionPolicyInputSchema' {
            # a simple test to create an object
            #$NewObject = Initialize-CreateProtectionPolicyInputSchema -Policy "TEST_VALUE" -ProtectionPolicyType "TEST_VALUE" -Schedules "TEST_VALUE"
            #$NewObject | Should -BeOfType CreateProtectionPolicyInputSchema
            #$NewObject.property | Should -Be 0
        }
    }
}
