#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.4.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'HostObject' {
    Context 'HostObject' {
        It 'Initialize-HostObject' {
            # a simple test to create an object
            #$NewObject = Initialize-HostObject -AssociatedLinks "TEST_VALUE" -AssociatedSystems "TEST_VALUE" -Comment "TEST_VALUE" -ConsoleUri "TEST_VALUE" -Contact "TEST_VALUE" -CustomerId "TEST_VALUE" -EditStatus "TEST_VALUE" -Fqdn "TEST_VALUE" -Generation "TEST_VALUE" -HostGroups "TEST_VALUE" -Id "TEST_VALUE" -Initiators "TEST_VALUE" -IpAddress "TEST_VALUE" -IsMergable "TEST_VALUE" -Location "TEST_VALUE" -MarkedForDelete "TEST_VALUE" -Model "TEST_VALUE" -Name "TEST_VALUE" -OperatingSystem "TEST_VALUE" -Persona "TEST_VALUE" -Protocol "TEST_VALUE" -Subnet "TEST_VALUE" -Systems "TEST_VALUE" -Type "TEST_VALUE" -UserCreated "TEST_VALUE"
            #$NewObject | Should -BeOfType HostObject
            #$NewObject.property | Should -Be 0
        }
    }
}
