#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.4.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'NimbleProtectionTemplateFieldsWithoutSortKey' {
    Context 'NimbleProtectionTemplateFieldsWithoutSortKey' {
        It 'Initialize-NimbleProtectionTemplateFieldsWithoutSortKey' {
            # a simple test to create an object
            #$NewObject = Initialize-NimbleProtectionTemplateFieldsWithoutSortKey -AgentHostname "TEST_VALUE" -AppClusterName "TEST_VALUE" -AppId "TEST_VALUE" -AppServer "TEST_VALUE" -AppServiceName "TEST_VALUE" -AppSync "TEST_VALUE" -CreationTime "TEST_VALUE" -Id "TEST_VALUE" -LastModified "TEST_VALUE" -Name "TEST_VALUE" -VcenterHostname "TEST_VALUE"
            #$NewObject | Should -BeOfType NimbleProtectionTemplateFieldsWithoutSortKey
            #$NewObject.property | Should -Be 0
        }
    }
}
