#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.4.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'NimbleSnapshotCommon' {
    Context 'NimbleSnapshotCommon' {
        It 'Initialize-NimbleSnapshotCommon' {
            # a simple test to create an object
            #$NewObject = Initialize-NimbleSnapshotCommon -AccessControlRecords "TEST_VALUE" -AgentType "TEST_VALUE" -AppUuid "TEST_VALUE" -AssociatedLinks "TEST_VALUE" -ConsoleUri "TEST_VALUE" -CreationTime "TEST_VALUE" -CustomerId "TEST_VALUE" -Description "TEST_VALUE" -ExpiryAfter "TEST_VALUE" -ExpiryTime "TEST_VALUE" -Generation "TEST_VALUE" -IsManuallyManaged "TEST_VALUE" -IsMfaProtected "TEST_VALUE" -IsReplica "TEST_VALUE" -IsUnmanaged "TEST_VALUE" -LastModified "TEST_VALUE" -Metadata "TEST_VALUE" -NewDataCompressedBytes "TEST_VALUE" -NewDataUncompressedBytes "TEST_VALUE" -NewDataValid "TEST_VALUE" -OfflineReason "TEST_VALUE" -OriginName "TEST_VALUE" -ResourceUri "TEST_VALUE" -Type "TEST_VALUE" -VolId "TEST_VALUE" -VolName "TEST_VALUE" -VpdIeee0 "TEST_VALUE" -VpdIeee1 "TEST_VALUE" -VpdT10 "TEST_VALUE"
            #$NewObject | Should -BeOfType NimbleSnapshotCommon
            #$NewObject.property | Should -Be 0
        }
    }
}
