#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.4.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'NimbleStorageSystemFieldsWithoutSortKey' {
    Context 'NimbleStorageSystemFieldsWithoutSortKey' {
        It 'Initialize-NimbleStorageSystemFieldsWithoutSortKey' {
            # a simple test to create an object
            #$NewObject = Initialize-NimbleStorageSystemFieldsWithoutSortKey -Id "TEST_VALUE" -Name "TEST_VALUE"
            #$NewObject | Should -BeOfType NimbleStorageSystemFieldsWithoutSortKey
            #$NewObject.property | Should -Be 0
        }
    }
}
