#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.4.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'NimblePerformanceHistoryData' {
    Context 'NimblePerformanceHistoryData' {
        It 'Initialize-NimblePerformanceHistoryData' {
            # a simple test to create an object
            #$NewObject = Initialize-NimblePerformanceHistoryData -CustomerId "TEST_VALUE" -EndTime "TEST_VALUE" -HistoryData "TEST_VALUE" -RequestUri "TEST_VALUE" -StartTime "TEST_VALUE"
            #$NewObject | Should -BeOfType NimblePerformanceHistoryData
            #$NewObject.property | Should -Be 0
        }
    }
}
