#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.4.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'NimbleDiskSmartAttributes' {
    Context 'NimbleDiskSmartAttributes' {
        It 'Initialize-NimbleDiskSmartAttributes' {
            # a simple test to create an object
            #$NewObject = Initialize-NimbleDiskSmartAttributes -CurValue "TEST_VALUE" -Flags "TEST_VALUE" -LastUpdatedEpochSecs "TEST_VALUE" -Name "TEST_VALUE" -RawValue "TEST_VALUE" -SmartId "TEST_VALUE" -Threshold "TEST_VALUE" -WorstValue "TEST_VALUE"
            #$NewObject | Should -BeOfType NimbleDiskSmartAttributes
            #$NewObject.property | Should -Be 0
        }
    }
}
