#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.4.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'RemoveRemoteCopyLinksInput' {
    Context 'RemoveRemoteCopyLinksInput' {
        It 'Initialize-RemoveRemoteCopyLinksInput' {
            # a simple test to create an object
            #$NewObject = Initialize-RemoveRemoteCopyLinksInput -ReplicationPartnerSystemId "TEST_VALUE" -Source "TEST_VALUE" -Target "TEST_VALUE"
            #$NewObject | Should -BeOfType RemoveRemoteCopyLinksInput
            #$NewObject.property | Should -Be 0
        }
    }
}
