#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.4.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'RemoteCopyLinks' {
    Context 'RemoteCopyLinks' {
        It 'Initialize-RemoteCopyLinks' {
            # a simple test to create an object
            #$NewObject = Initialize-RemoteCopyLinks -Items "TEST_VALUE" -Total "TEST_VALUE"
            #$NewObject | Should -BeOfType RemoteCopyLinks
            #$NewObject.property | Should -Be 0
        }
    }
}
