#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.4.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'VolumePerformance' {
    Context 'VolumePerformance' {
        It 'Initialize-VolumePerformance' {
            # a simple test to create an object
            #$NewObject = Initialize-VolumePerformance -Iops "TEST_VALUE" -LatencyMs "TEST_VALUE" -RequestUri "TEST_VALUE" -ResourceUri "TEST_VALUE" -ThroughputKbps "TEST_VALUE"
            #$NewObject | Should -BeOfType VolumePerformance
            #$NewObject.property | Should -Be 0
        }
    }
}
