#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.4.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'FileServersApi' {
    Context 'Invoke-DeviceType6GetMetricsHistory' {
        It 'Test Invoke-DeviceType6GetMetricsHistory' {
            #$TestResult = Invoke-DeviceType6GetMetricsHistory -SystemUuid "TEST_VALUE" -Range "TEST_VALUE" -TimeIntervalMin "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-DeviceType6GetPerformanceStatistics' {
        It 'Test Invoke-DeviceType6GetPerformanceStatistics' {
            #$TestResult = Invoke-DeviceType6GetPerformanceStatistics -SystemUuid "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-DeviceType6GetSystemByUUID' {
        It 'Test Invoke-DeviceType6GetSystemByUUID' {
            #$TestResult = Invoke-DeviceType6GetSystemByUUID -SystemUuid "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-DeviceType6ListSystems' {
        It 'Test Invoke-DeviceType6ListSystems' {
            #$TestResult = Invoke-DeviceType6ListSystems -Limit "TEST_VALUE" -Offset "TEST_VALUE" -Filter "TEST_VALUE" -Sort "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
