#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.4.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Edit Nimble local key manager input.

.PARAMETER Active
Whether the master key is active or not. Possible values: 'true', 'false'.
.PARAMETER NewPassphrase
New passphrase for local key manager. String with size from 8 to 64 printable characters.
.PARAMETER Passphrase
Existing passphrase  for local key manager. String with size from 8 to 64 printable characters.
.OUTPUTS

EditLocalKeyManager<PSCustomObject>
#>

function Initialize-EditLocalKeyManager {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${Active},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${NewPassphrase},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Passphrase}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => EditLocalKeyManager' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "active" = ${Active}
            "new_passphrase" = ${NewPassphrase}
            "passphrase" = ${Passphrase}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to EditLocalKeyManager<PSCustomObject>

.DESCRIPTION

Convert from JSON to EditLocalKeyManager<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

EditLocalKeyManager<PSCustomObject>
#>
function ConvertFrom-JsonToEditLocalKeyManager {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => EditLocalKeyManager' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in EditLocalKeyManager
        $AllProperties = ("active", "new_passphrase", "passphrase")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "active"))) { #optional property not found
            $Active = $null
        } else {
            $Active = $JsonParameters.PSobject.Properties["active"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "new_passphrase"))) { #optional property not found
            $NewPassphrase = $null
        } else {
            $NewPassphrase = $JsonParameters.PSobject.Properties["new_passphrase"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "passphrase"))) { #optional property not found
            $Passphrase = $null
        } else {
            $Passphrase = $JsonParameters.PSobject.Properties["passphrase"].value
        }

        $PSO = [PSCustomObject]@{
            "active" = ${Active}
            "new_passphrase" = ${NewPassphrase}
            "passphrase" = ${Passphrase}
        }

        return $PSO
    }

}

