#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.4.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

Enum NamePattern.

.DESCRIPTION

name pattern
#>

enum NamePattern {
    # enum value: "PARENT_TIMESTAMP"
    PARENT_TIMESTAMP
    # enum value: "PARENT_SEC_SINCE_EPOCH"
    PARENT_SEC_SINCE_EPOCH
    # enum value: "CUSTOM"
    CUSTOM
}

