#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.4.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Request body for  shelves activation workflow

.PARAMETER ShelfList
List of shelves details.
.OUTPUTS

NimbleShelvesActivateInput<PSCustomObject>
#>

function Initialize-NimbleShelvesActivateInput {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${ShelfList}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => NimbleShelvesActivateInput' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $ShelfList) {
            throw "invalid value for 'ShelfList', 'ShelfList' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "shelf_list" = ${ShelfList}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to NimbleShelvesActivateInput<PSCustomObject>

.DESCRIPTION

Convert from JSON to NimbleShelvesActivateInput<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

NimbleShelvesActivateInput<PSCustomObject>
#>
function ConvertFrom-JsonToNimbleShelvesActivateInput {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => NimbleShelvesActivateInput' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in NimbleShelvesActivateInput
        $AllProperties = ("shelf_list")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'shelf_list' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "shelf_list"))) {
            throw "Error! JSON cannot be serialized due to the required property 'shelf_list' missing."
        } else {
            $ShelfList = $JsonParameters.PSobject.Properties["shelf_list"].value
        }

        $PSO = [PSCustomObject]@{
            "shelf_list" = ${ShelfList}
        }

        return $PSO
    }

}

