#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.3.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ArcusportISCSIEditVlansInner' {
    Context 'ArcusportISCSIEditVlansInner' {
        It 'Initialize-ArcusportISCSIEditVlansInner' {
            # a simple test to create an object
            #$NewObject = Initialize-ArcusportISCSIEditVlansInner -IpAddress "TEST_VALUE" -Mtu "TEST_VALUE" -NetMask "TEST_VALUE" -SendTargetGroupTag "TEST_VALUE" -VlanId "TEST_VALUE"
            #$NewObject | Should -BeOfType ArcusportISCSIEditVlansInner
            #$NewObject.property | Should -Be 0
        }
    }
}
