#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.3.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ArcusenclosureCdmDetails' {
    Context 'ArcusenclosureCdmDetails' {
        It 'Initialize-ArcusenclosureCdmDetails' {
            # a simple test to create an object
            #$NewObject = Initialize-ArcusenclosureCdmDetails -CustomerId "TEST_VALUE" -Displayname "TEST_VALUE" -Domain "TEST_VALUE" -ElementStatusCode "TEST_VALUE" -EnclosureId "TEST_VALUE" -EnclosureUid "TEST_VALUE" -FailInd "TEST_VALUE" -FwVersion "TEST_VALUE" -Generation "TEST_VALUE" -Id "TEST_VALUE" -Manufacturing "TEST_VALUE" -OkInt "TEST_VALUE" -OsVersion "TEST_VALUE" -PUid "TEST_VALUE" -SafeToRemove "TEST_VALUE" -SystemId "TEST_VALUE" -Type "TEST_VALUE" -Updating "TEST_VALUE"
            #$NewObject | Should -BeOfType ArcusenclosureCdmDetails
            #$NewObject.property | Should -Be 0
        }
    }
}
