#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.3.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'FleetVolumeSetDetails' {
    Context 'FleetVolumeSetDetails' {
        It 'Initialize-FleetVolumeSetDetails' {
            # a simple test to create an object
            #$NewObject = Initialize-FleetVolumeSetDetails -AppType "TEST_VALUE" -Application "TEST_VALUE" -AssociatedLinks "TEST_VALUE" -CustomerId "TEST_VALUE" -Generation "TEST_VALUE" -Id "TEST_VALUE" -Name "TEST_VALUE" -ProductFamily "TEST_VALUE" -ResourceUri "TEST_VALUE" -SystemId "TEST_VALUE" -Type "TEST_VALUE"
            #$NewObject | Should -BeOfType FleetVolumeSetDetails
            #$NewObject.property | Should -Be 0
        }
    }
}
