#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.3.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'GetSystemSettingsResponseSyslogdSettings' {
    Context 'GetSystemSettingsResponseSyslogdSettings' {
        It 'Initialize-GetSystemSettingsResponseSyslogdSettings' {
            # a simple test to create an object
            #$NewObject = Initialize-GetSystemSettingsResponseSyslogdSettings -Protocol "TEST_VALUE" -SyslogdEnabled "TEST_VALUE" -SyslogdHost "TEST_VALUE" -SyslogdPort "TEST_VALUE"
            #$NewObject | Should -BeOfType GetSystemSettingsResponseSyslogdSettings
            #$NewObject.property | Should -Be 0
        }
    }
}
