#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.3.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'NodeDetails' {
    Context 'NodeDetails' {
        It 'Initialize-NodeDetails' {
            # a simple test to create an object
            #$NewObject = Initialize-NodeDetails -NodeId "TEST_VALUE" -AssociatedLinks "TEST_VALUE" -BiosVersion "TEST_VALUE" -CacheAvailablePct "TEST_VALUE" -CacheEnabled "TEST_VALUE" -ConsoleUri "TEST_VALUE" -ControlMemoryMiB "TEST_VALUE" -CustomerId "TEST_VALUE" -DataMemoryMiB "TEST_VALUE" -Displayname "TEST_VALUE" -Domain "TEST_VALUE" -Generation "TEST_VALUE" -Id "TEST_VALUE" -InCluster "TEST_VALUE" -KernelVersion "TEST_VALUE" -LocateEnabled "TEST_VALUE" -Manufacturing "TEST_VALUE" -Master "TEST_VALUE" -Name "TEST_VALUE" -Online "TEST_VALUE" -RequestUri "TEST_VALUE" -ResourceUri "TEST_VALUE" -SafeToRemove "TEST_VALUE" -ServiceLED "TEST_VALUE" -State "TEST_VALUE" -StateDescription "TEST_VALUE" -SystemId "TEST_VALUE" -SystemLED "TEST_VALUE" -Type "TEST_VALUE" -Uptime "TEST_VALUE"
            #$NewObject | Should -BeOfType NodeDetails
            #$NewObject.property | Should -Be 0
        }
    }
}
