#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.3.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'NodeMcuList' {
    Context 'NodeMcuList' {
        It 'Initialize-NodeMcuList' {
            # a simple test to create an object
            #$NewObject = Initialize-NodeMcuList -AssociatedLinks "TEST_VALUE" -CustomerId "TEST_VALUE" -Domain "TEST_VALUE" -FwVersion "TEST_VALUE" -Generation "TEST_VALUE" -Id "TEST_VALUE" -Model "TEST_VALUE" -Name "TEST_VALUE" -NodeDeviceId "TEST_VALUE" -NodeId "TEST_VALUE" -ResetReason "TEST_VALUE" -ResourceUri "TEST_VALUE" -State "TEST_VALUE" -SystemId "TEST_VALUE" -Type "TEST_VALUE" -Uptime "TEST_VALUE"
            #$NewObject | Should -BeOfType NodeMcuList
            #$NewObject.property | Should -Be 0
        }
    }
}
