#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.3.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'SupportSettingsPatchRequest' {
    Context 'SupportSettingsPatchRequest' {
        It 'Initialize-SupportSettingsPatchRequest' {
            # a simple test to create an object
            #$NewObject = Initialize-SupportSettingsPatchRequest -AllowRemoteAccess "TEST_VALUE" -BundleEnabled "TEST_VALUE" -BundleInterval "TEST_VALUE" -CompressMethod "TEST_VALUE" -Customer "TEST_VALUE" -Location "TEST_VALUE" -LogEnabled "TEST_VALUE" -LogInterval "TEST_VALUE" -RtsEnabled "TEST_VALUE" -SendCallHome "TEST_VALUE" -Site "TEST_VALUE"
            #$NewObject | Should -BeOfType SupportSettingsPatchRequest
            #$NewObject.property | Should -Be 0
        }
    }
}
