#
# Data Services Cloud Console API
# Data Services Cloud Console API
# Version: 1.3.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'VolumeSetApplicationType' {
    Context 'VolumeSetApplicationType' {
        It 'Initialize-VolumeSetApplicationType' {
            # a simple test to create an object
            #$NewObject = Initialize-VolumeSetApplicationType
            #$NewObject | Should -BeOfType VolumeSetApplicationType
            #$NewObject.property | Should -Be 0
        }
    }
}
